### PR TITLE
Fixed REST/GraphQL tutorials links

### PR DESCRIPTION
**Pull request by oilart**
Fixed links for the tutorials. We could also create `REST` and `GraphQL` folders inside `NSTTutorials` but so far all REST examples are clearly grouped/stated in README.

### CODE REVIEW

**Review by jdesmarais-ebay — APPROVED** [review]
Thanks for fixing this!

**Review by juliandesmarais — APPROVED** [review]
Thanks for fixing this!

**Comment by juliandesmarais** [comment]
retest

**Comment by juliandesmarais** [comment]
Tests are passing, merging, will look into CI permissions issue separately

**Pull request merged**
